import Sidebar from "@/components/shared/Sidebar";
import { RxDashboard } from "react-icons/rx";
import { FaBox, FaList, FaStar, FaBook, FaUniversity } from "react-icons/fa";
import AdminHeader from "@/components/admin/AdminHeader";

export const metadata = {
  title: "Provider",
  description: "Generated by create next app",
};
const navLinks = [
  {
    section: "",
    items: [
      { label: "Dashboard", icon: <RxDashboard />, path: "/provider" },
      {
        label: "My Services",
        icon: <RxDashboard />,
        path: "/provider/my-services",
      },
      { label: "Bookings", icon: <RxDashboard />, path: "/provider/bookings" },
      { label: "Staffs", icon: <RxDashboard />, path: "/provider/staffs" },
      {
        label: "Customers",
        icon: <RxDashboard />,
        path: "/provider/customers",
      },
      { label: "Payout", icon: <RxDashboard />, path: "/provider/payout" },
      {
        label: "Holidays & Leave",
        icon: <RxDashboard />,
        path: "/provider/holidays-leave",
      },
      { label: "Coupons", icon: <RxDashboard />, path: "/provider/coupons" },
      { label: "Offers", icon: <RxDashboard />, path: "/provider/offers" },
      { label: "Reviews", icon: <RxDashboard />, path: "/provider/reviews" },
      { label: "Equiries", icon: <RxDashboard />, path: "/provider/equiries" },
      { label: "Earnings", icon: <RxDashboard />, path: "/provider/earnings" },
      { label: "Chat", icon: <RxDashboard />, path: "/provider/chat" },
      { label: "Settings", icon: <FaBook />, path: "/provider/settings" },
      { label: "Logout", icon: <FaBook />, path: "/" },
    ],
  },
];

export default function AdminLayout({ children }) {
  return (
    <div className="min-h-screen ">
      <div className="flex">
        {/* Sidebar */}
        <Sidebar navLinks={navLinks} role="provider" />
        {/* Main Content */}
        <div className="flex-1 flex flex-col min-w-0">
          {/* Topbar */}
          <AdminHeader />
          {/* Page Content */}
          <main className="flex-1 px-6  bg-[#ffffff] pt-20">{children}</main>
        </div>
      </div>
    </div>
  );
}
