import Sidebar from "@/components/shared/Sidebar";
import { RxDashboard } from "react-icons/rx";
import { FaBox, FaList, FaStar, FaBook, FaUniversity } from "react-icons/fa";
import AdminHeader from "@/components/admin/AdminHeader";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};
const navLinks = [
  {
    section: "Home",
    items: [{ label: "Dashboard", icon: <RxDashboard />, path: "/admin" }],
  },
  {
    section: "Services",
    items: [
      {
        label: "Services",
        icon: <FaBox />,
        children: [
          { label: "Add Service", path: "/admin/services/add-service" },
          { label: "Services", path: "/admin/services" },
          {
            label: "Service Settings",
            path: "/admin/services/service-settings",
          },
        ],
      },
      { label: "Categories", icon: <FaList />, path: "/admin/categories" },
      {
        label: "Sub Categories",
        icon: <FaList />,
        path: "/admin/sub-categories",
      },
      {
        label: "Review",
        icon: <FaStar />,
        children: [
          { label: "Review Type", path: "/admin/reviews/review-type" },
          { label: "Review", path: "/admin/reviews" },
        ],
      },
    ],
  },
  {
    section: "Booking",
    items: [{ label: "Bookings", icon: <FaBook />, path: "/admin/booking" }],
  },
  {
    section: "Finance & Accounts",
    items: [
      // {
      //   label: "Bank Transfer",
      //   icon: <FaUniversity />,
      //   path: "/admin/bank-transfer",
      // },
      // { label: "Wallet", icon: <FaList />, path: "/admin/wallet" },
      // {
      //   label: "ReFund Request",
      //   icon: <FaList />,
      //   path: "/admin/refund-request",
      // },
      {
        label: "Cash on Delivery",
        icon: <FaList />,
        path: "/admin/cash-on-delivery",
      },
      // {
      //   label: "Payouts",
      //   icon: <FaList />,
      //   children: [
      //     { label: "Payout Requests", path: "/admin/payouts" },
      //     { label: "Payout Settings", path: "/admin/payouts/payout-settings" },
      //   ],
      // },
      // { label: "Sales Transactions", icon: <FaList />, path: "/admin" },
    ],
  },
  // {
  //   section: "Others",
  //   items: [{ label: "Chat", icon: <FaBook />, path: "/admin" }],
  // },
  {
    section: "Contents",
    items: [
      {
        label: "Pages",
        icon: <FaBook />,
        children: [
          { label: "Add Page", path: "/admin/pages/add-page" },
          { label: "Pages", path: "/admin/pages" },
          { label: "Pages List", path: "/admin/pages/page-list" },
        ],
      },
      {
        label: "Blog",
        icon: <FaBook />,
        children: [
          { label: "All Blog", path: "/admin/blogs" },
          { label: "Add Blog", path: "/admin/blogs/add-blog" },
          { label: "Categories", path: "/admin/blogs/blog-category" },
          { label: "Blog Comments", path: "/admin/blogs/blog-comments" },
        ],
      },
      {
        label: "Location",
        icon: <FaBook />,
        children: [
          { label: "Countries", path: "/admin/location/countries" },
          { label: "States", path: "/admin/location/states" },
          { label: "Cities", path: "/admin/location/cities" },
        ],
      },
      { label: "Testimonials", icon: <FaBook />, path: "/admin/testimonials" },
      { label: "FAQ", icon: <FaBook />, path: "/admin/faq" },
    ],
  },
  // {
  //   section: "Membership",
  //   items: [
  //     { label: "Membership", icon: <FaBook />, path: "/bookings" },
  //     { label: "Membership Addons", icon: <FaBook />, path: "/bookings" },
  //   ],
  // },
  // {
  //   section: "Reports",
  //   items: [
  //     { label: "Admin Earnings", icon: <FaBook />, path: "/bookings" },
  //     { label: "Provider Earnings", icon: <FaBook />, path: "/bookings" },
  //     { label: "Provider Sales", icon: <FaBook />, path: "/bookings" },
  //     { label: "Provider Wallet", icon: <FaBook />, path: "/bookings" },
  //     { label: "Customer Wallet", icon: <FaBook />, path: "/bookings" },
  //     { label: "Membership transaction", icon: <FaBook />, path: "/bookings" },
  //     { label: "Refund Report", icon: <FaBook />, path: "/bookings" },
  //     { label: "Register Report", icon: <FaBook />, path: "/bookings" },
  //     { label: "Sales Report", icon: <FaBook />, path: "/bookings" },
  //   ],
  // },
  {
    section: "User Management",
    items: [
      {
        label: "Users",
        icon: <FaBook />,
        children: [
          { label: "Users", path: "/admin/users" },
          { label: "Customers", path: "/admin/users/customers" },
          { label: "Providers", path: "/admin/users/providers" },
        ],
      },
      {
        label: "Roles & Permissions",
        icon: <FaBook />,
        path: "/admin/roles-permissions",
      },
      {
        label: "Delete Account Requests",
        icon: <FaBook />,
        path: "/admin/delete-account-requests",
      },
      {
        label: "Verification Requests",
        icon: <FaBook />,
        path: "/admin/verification-requests",
      },
    ],
  },
  {
    section: "Marketing",
    items: [
      { label: "Coupons", icon: <FaBook />, path: "/admin/coupons" },
      // { label: "Service Offers", icon: <FaBook />, path: "/bookings" },
      // { label: "Features Services", icon: <FaBook />, path: "/bookings" },
      // { label: "Email Newsletter", icon: <FaBook />, path: "/bookings" },
    ],
  },
  // {
  //   section: "Management",
  //   items: [
  //     { label: "Cache System", icon: <FaBook />, path: "/bookings" },
  //     { label: "Email Templates", icon: <FaBook />, path: "/bookings" },
  //     { label: "SMS Templates", icon: <FaBook />, path: "/bookings" },
  //     { label: "Menu Management", icon: <FaBook />, path: "/bookings" },
  //     { label: "Widgets", icon: <FaBook />, path: "/bookings" },
  //     { label: "Create Menu", icon: <FaBook />, path: "/bookings" },
  //     { label: "Plugin Managers", icon: <FaBook />, path: "/bookings" },
  //   ],
  // },
  // {
  //   section: "Support",
  //   items: [
  //     { label: "Contact Messages", icon: <FaBook />, path: "/bookings" },
  //     { label: "Abuse Reports", icon: <FaBook />, path: "/bookings" },
  //     { label: "Announcements", icon: <FaBook />, path: "/bookings" },
  //   ],
  // },
  {
    section: "Settings",
    items: [
      // { label: "Settings", icon: <FaBook />, path: "/bookings" },
      { label: "Logout", icon: <FaBook />, path: "/" },
    ],
  },
];

export default function AdminLayout({ children }) {
  return (
    <div className="min-h-screen ">
      <div className="flex">
        {/* Sidebar */}
        <Sidebar navLinks={navLinks} role="admin" />
        {/* Main Content */}
        <div className="flex-1 flex flex-col min-w-0">
          {/* Topbar */}
          <AdminHeader />
          {/* Page Content */}
          <main className="flex-1 px-6  bg-[#ffffff]">{children}</main>
        </div>
      </div>
    </div>
  );
}
