import Sidebar from "@/components/shared/Sidebar";
import { RxDashboard } from "react-icons/rx";
import { FaBox, FaList, FaStar, FaBook, FaUniversity } from "react-icons/fa";
import AdminHeader from "@/components/admin/AdminHeader";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};
const navLinks = [
  {
    section: "Home",
    items: [{ label: "Dashboard", icon: <RxDashboard />, path: "/admin" }],
  },
  {
    section: "Services",
    items: [
      {
        label: "Services",
        icon: <FaBox />,
        children: [
          { label: "Add Service", path: "/services/add" },
          { label: "Services", path: "/services" },
          { label: "Service Settings", path: "/services/settings" },
        ],
      },
      { label: "Categories", icon: <FaList />, path: "/categories" },
      { label: "Sub Categories", icon: <FaList />, path: "/sub-categories" },
      {
        label: "Review",
        icon: <FaStar />,
        children: [
          { label: "Review Type", path: "/reviews" },
          { label: "Review", path: "/reviews/pending" },
        ],
      },
    ],
  },
  {
    section: "Booking",
    items: [{ label: "Bookings", icon: <FaBook />, path: "/bookings" }],
  },
  {
    section: "Finance & Accounts",
    items: [
      {
        label: "Bank Transfer",
        icon: <FaUniversity />,
        path: "/bank-transfer",
      },
      { label: "Wallet", icon: <FaList />, path: "/categories" },
      { label: "ReFound Request", icon: <FaList />, path: "/categories" },
      { label: "Cash on Delivery", icon: <FaList />, path: "/categories" },
      {
        label: "Payouts",
        icon: <FaList />,
        children: [
          { label: "Payout Requests", path: "/reviews" },
          { label: "Payout Settings", path: "/reviews/pending" },
        ],
      },
      { label: "Sales Transactions", icon: <FaList />, path: "/categories" },
    ],
  },
  {
    section: "Others",
    items: [{ label: "Chat", icon: <FaBook />, path: "/bookings" }],
  },
  {
    section: "Contents",
    items: [
      {
        label: "Pages",
        icon: <FaBook />,
        children: [
          { label: "Add Page", path: "/reviews" },
          { label: "Pages", path: "/reviews/pending" },
          { label: "Pages List", path: "/reviews/pending" },
        ],
      },
      {
        label: "Blog",
        icon: <FaBook />,
        children: [
          { label: "All Blog", path: "/reviews" },
          { label: "Add Blog", path: "/reviews/pending" },
          { label: "Categories", path: "/reviews/pending" },
          { label: "Blog Comments", path: "/reviews/pending" },
        ],
      },
      {
        label: "Location",
        icon: <FaBook />,
        children: [
          { label: "Countries", path: "/reviews" },
          { label: "States", path: "/reviews/pending" },
          { label: "Cities", path: "/reviews/pending" },
        ],
      },
      { label: "Testimonials", icon: <FaBook />, path: "/bookings" },
      { label: "FAQ", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Membership",
    items: [
      { label: "Membership", icon: <FaBook />, path: "/bookings" },
      { label: "Membership Addons", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Reports",
    items: [
      { label: "Admin Earnings", icon: <FaBook />, path: "/bookings" },
      { label: "Provider Earnings", icon: <FaBook />, path: "/bookings" },
      { label: "Provider Sales", icon: <FaBook />, path: "/bookings" },
      { label: "Provider Wallet", icon: <FaBook />, path: "/bookings" },
      { label: "Customer Wallet", icon: <FaBook />, path: "/bookings" },
      { label: "Membership transaction", icon: <FaBook />, path: "/bookings" },
      { label: "Refund Report", icon: <FaBook />, path: "/bookings" },
      { label: "Register Report", icon: <FaBook />, path: "/bookings" },
      { label: "Sales Report", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "User Management",
    items: [
      {
        label: "Users",
        icon: <FaBook />,
        children: [
          { label: "Users", path: "/reviews" },
          { label: "Customers", path: "/reviews/pending" },
          { label: "Providers", path: "/reviews/pending" },
        ],
      },
      { label: "Roles & Permissions", icon: <FaBook />, path: "/bookings" },
      { label: "Delete Account Requests", icon: <FaBook />, path: "/bookings" },
      { label: "Verification Requests", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Marketing",
    items: [
      { label: "Coupons", icon: <FaBook />, path: "/bookings" },
      { label: "Service Offers", icon: <FaBook />, path: "/bookings" },
      { label: "Features Services", icon: <FaBook />, path: "/bookings" },
      { label: "Email Newsletter", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Management",
    items: [
      { label: "Cache System", icon: <FaBook />, path: "/bookings" },
      { label: "Email Templates", icon: <FaBook />, path: "/bookings" },
      { label: "SMS Templates", icon: <FaBook />, path: "/bookings" },
      { label: "Menu Management", icon: <FaBook />, path: "/bookings" },
      { label: "Widgets", icon: <FaBook />, path: "/bookings" },
      { label: "Create Menu", icon: <FaBook />, path: "/bookings" },
      { label: "Plugin Managers", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Support",
    items: [
      { label: "Contact Messages", icon: <FaBook />, path: "/bookings" },
      { label: "Abuse Reports", icon: <FaBook />, path: "/bookings" },
      { label: "Announcements", icon: <FaBook />, path: "/bookings" },
    ],
  },
  {
    section: "Settings",
    items: [
      { label: "Settings", icon: <FaBook />, path: "/bookings" },
      { label: "Logout", icon: <FaBook />, path: "/bookings" },
    ],
  },
];

export default function AdminLayout({ children }) {
  return (
    <div className="min-h-screen ">
      <div className="flex">
        {/* Sidebar */}
        <Sidebar navLinks={navLinks} />
        {/* Main Content */}
        <div className="flex-1 flex flex-col min-w-0">
          {/* Topbar */}
          <AdminHeader />
          {/* Page Content */}
          <main className="flex-1 p-4 md:p-8 bg-[#ffffff]">{children}</main>
        </div>
      </div>
    </div>
  );
}
