import Header from "@/components/shared/Header";

export const metadata = {
  title: "Truelly Sell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />
        <div className="my-20"> {children}</div>
      </body>
    </html>
  );
}
