import Sidebar from "@/components/shared/Sidebar";
import { RxDashboard } from "react-icons/rx";
import { FaBox, FaList, FaStar, FaBook, FaUniversity } from "react-icons/fa";
import AdminHeader from "@/components/admin/AdminHeader";

export const metadata = {
  title: "Provider",
  description: "Generated by create next app",
};
const navLinks = [
  {
    section: "",
    items: [
      { label: "Dashboard", icon: <RxDashboard />, path: "/customer" },
      { label: "Booking", icon: <RxDashboard />, path: "/customer/booking" },
    ],
  },
];

export default function AdminLayout({ children }) {
  return (
    <div className="min-h-screen ">
      <div className="flex">
        {/* Sidebar */}
        <Sidebar navLinks={navLinks} role="customer" />
        {/* Main Content */}
        <div className="flex-1 flex flex-col min-w-0">
          {/* Topbar */}
          <AdminHeader />
          {/* Page Content */}
          <main className="flex-1 px-6  bg-[#ffffff]">{children}</main>
        </div>
      </div>
    </div>
  );
}
